'use strict';
/**
 * Angular service to load the catalog form JSON.
 *
 * Example usage
 CatalogService.getList(<optional filter name>).then(function(result) {
    $scope.data = result;
 });
 *
 * Catalog generated by scripts in tools/ directory
 * Must follow image naming conventions for all of this to work properly
 * See the README.md file
 */
angular.module('stemStore')
  .factory('CatalogService', function($http, $q) {
  var baseUrl = 'assets/json/catalog.json';
  var catalogResponse = {};
  return {
    baseUrl: baseUrl,
    getList : function(filter) {
      var deferred = $q.defer();
      $http.get(baseUrl).then(function(result) {
        catalogResponse = [];
        if (filter) {
          for (var i in result.data.data) {
            if (result.data.data[i].catalog === filter) {
              catalogResponse = [result.data.data[i]];
            }
          }
        } else {
          catalogResponse = result.data.data;
        }
        deferred.resolve(catalogResponse);
      });
      return deferred.promise;
    }
  };
});
